export { ReactComponent as IconBalance } from './icon-balance.svg'
export { ReactComponent as IconBet } from './icon-bet.svg'
export { ReactComponent as IconSets } from './icon-sets.svg'
export { ReactComponent as IconUndo } from './icon-undo.svg'
export { ReactComponent as IconDouble } from './icon-double.svg'
export { ReactComponent as IconHeatMapWhite } from './icon-heat-map-white.svg'
export { ReactComponent as IconHeatMapWhiteActive } from './icon-heat-map-white-active.svg'
export { ReactComponent as IconAutoPlay } from './icon-autoplay.svg'
export { ReactComponent as IconHamgurgerMenu } from './icon-hamburger-menu.svg'
export { ReactComponent as IconFavorites } from './icon-favorites.svg'
export { ReactComponent as IconStatics } from './icon-statics.svg'

export { ReactComponent as IconPlay } from './icon-play.svg'
export { ReactComponent as IconPlay2 } from './icon-play2.svg'
export { ReactComponent as IconSend } from './icon-send.svg'
export { ReactComponent as IconIce } from './icon-ice.svg'
export { ReactComponent as IconFire } from './icon-fire.svg'
export { ReactComponent as IconClose } from './icon-close.svg'
export { ReactComponent as IconStatics2 } from './icon-statics2.svg'
export { ReactComponent as IconFavorites2 } from './icon-favorites2.svg'
export { ReactComponent as IconPlus } from './icon-plus.svg'
export { ReactComponent as IconTileRed } from './icon-tile-red.svg'
export { ReactComponent as IconTileBlack } from './icon-tile-black.svg'
export { ReactComponent as Chip3 } from './chip-3.svg'
export { ReactComponent as Chip5 } from './chip-5.svg'
export { ReactComponent as Chip10 } from './chip-10.svg'
export { ReactComponent as Chip20 } from './chip-20.svg'
export { ReactComponent as Chip30 } from './chip-30.svg'
export { ReactComponent as Chip50 } from './chip-50.svg'
export { ReactComponent as Chip100 } from './chip-100.svg'
export { ReactComponent as IconArrowRight } from './icon-arrow-right.svg'
export { ReactComponent as IconGoToLobby } from './icon-go-to-lobby.svg'
export { ReactComponent as IconHow } from './icon-how.svg'
export { ReactComponent as IconSettings } from './icon-settings.svg'
export { ReactComponent as IconBetHistory } from './icon-bet-history.svg'
export { ReactComponent as IconLimits } from './icon-limits.svg'
export { ReactComponent as IconMessage } from './icon-message.svg'
export { ReactComponent as IconLogoLivegames } from './icon-logo-livegames.svg'
export { ReactComponent as IconLivegames } from './icon-livegames.svg'
export { ReactComponent as IconArrowLeft } from './icon-arrow-left.svg'
export { ReactComponent as IconArrowUp } from './icon-arrow-up.svg'
export { ReactComponent as IconArrowDown } from './icon-arrow-down.svg'
export { ReactComponent as IconVolume } from './icon-volume.svg'
export { ReactComponent as IconVolumeMute } from './icon-volume-mute.svg'
export { ReactComponent as IconTr } from './icon-tr.svg'
export { ReactComponent as IconUs } from './icon-us.svg'
export { ReactComponent as IconRu } from './icon-ru.svg'
export { ReactComponent as IconSa } from './icon-sa.svg'
export { ReactComponent as IconBp } from './icon-bp.svg'
export { ReactComponent as IconPt } from './icon-pt.svg'
export { ReactComponent as IconDe } from './icon-de.svg'
export { ReactComponent as IconUz } from './icon-uz.svg'
export { ReactComponent as IconCheck } from './icon-check.svg'
export { ReactComponent as IconPencil } from './icon-pencil.svg'
export { ReactComponent as IconMinus } from './icon-minus.svg'
export { ReactComponent as IconPlus2 } from './icon-plus2.svg'
export { ReactComponent as IconPupa } from './icon-pupa.svg'
export { ReactComponent as IconTrash } from './icon-trash.svg'
export { ReactComponent as IconSuccess } from './icon-success.svg'
export { ReactComponent as IconError } from './icon-error.svg'
export { ReactComponent as IconInfo } from './icon-info.svg'
export { ReactComponent as IconWarning } from './icon-warning.svg'
export { ReactComponent as IconRepeat } from './icon-repeat.svg'
export { ReactComponent as IconRepeat2 } from './icon-repeat2.svg'
export { ReactComponent as IconDelete } from './icon-delete.svg'
export { ReactComponent as IconWinning } from './icon-winning.svg'
export { ReactComponent as IconWinningDesktop } from './icon-winning-desktop.svg'

export { ReactComponent as IconWinningEn } from './icon-winning-en.svg'
export { ReactComponent as IconWinningRu } from './icon-winning-ru.svg'
export { ReactComponent as IconWinningPo } from './icon-winning-po.svg'
export { ReactComponent as IconWinningSh } from './icon-winning-sh.svg'

export { ReactComponent as IconWinningEnDesktop } from './icon-winning-en-desktop.svg'
export { ReactComponent as IconWinningRuDesktop } from './icon-winning-ru-desktop.svg'
export { ReactComponent as IconWinningPoDesktop } from './icon-winning-po-desktop.svg'
export { ReactComponent as IconWinningShDesktop } from './icon-winning-sh-desktop.svg'

export { ReactComponent as WinningNumber0 } from './winning-number-0.svg'
export { ReactComponent as WinningNumber26 } from './winning-number-26.svg'
export { ReactComponent as WinningNumber32 } from './winning-number-32.svg'
export { ReactComponent as WinningNumberBlack } from './winning-number-black.svg'
export { ReactComponent as WinningNumberRed } from './winning-number-red.svg'

export { ReactComponent as IconSwipeLeft } from './icon-swipe-left.svg'
export { ReactComponent as IconSwipeRight } from './icon-swipe-right.svg'
export { ReactComponent as IconGesture } from './icon-gesture.svg'

export { ReactComponent as Step1 } from './step-1.svg'
export { ReactComponent as Step2 } from './step-2.svg'
export { ReactComponent as Step3 } from './step-3.svg'

export { ReactComponent as Step1Active } from './step-1-active.svg'
export { ReactComponent as Step2Active } from './step-2-active.svg'
export { ReactComponent as Step3Active } from './step-3-active.svg'
export { ReactComponent as IconStop } from './icon-stop.svg'
export { ReactComponent as IconBack } from './icon-back.svg'
export { ReactComponent as IconPeopleCount } from './icon-people-count.svg'
export { ReactComponent as IconReward } from './icon-reward.svg'

export { ReactComponent as IconMaximizeGrid } from './icon-maximize-grid.svg'
export { ReactComponent as IconMinimizeGrid } from './icon-minimize-grid.svg'

export { ReactComponent as IconMaximize } from './icon-maximize.svg'
export { ReactComponent as IconMinimize } from './icon-minimize.svg'
export { ReactComponent as IconPin } from './icon-pin.svg'

export { ReactComponent as IconVolumeGrey } from './icon-volume-grey.svg'
export { ReactComponent as IconVolumeMuteGrey } from './icon-volume-mute-grey.svg'
export { ReactComponent as IconEdit } from './icon-edit.svg'

// Vip
export { IconStaticsVip } from './icon-statics-vip'
export { ButtonBaseVip } from './button-base-vip'
export { ReactComponent as IconMinimizeGridVip } from './icon-minimize-grid-vip.svg'
export { ReactComponent as IconHamburgerMenuVip } from './icon-menu-vip.svg'
export { IconHeatMapVip } from './icon-heat-map-vip'
export { ReactComponent as IconVolumeVip } from './icon-volume-vip.svg'
export { IconRaceTrackVip } from './icon-racetrack-vip'
export { BetGridVip } from './bet-grid-vip'
export { Wheel } from './wheel'
export { ReactComponent as BetGridVipOutline } from './bet-grid-vip-outline.svg'
export { ReactComponent as BottomBarLeftCorner } from './bottom-bar-left-corner.svg'
export { ReactComponent as BottomBarRightCorner } from './bottom-bar-right-corner.svg'
export { ReactComponent as IconDeleteVip } from './icon-delete-vip.svg'
export { ReactComponent as IconFavoritesVip } from './icon-favorites-vip.svg'
export { ReactComponent as IconUndoVip } from './icon-undo-vip.svg'
export { ReactComponent as IconRepeatVip } from './icon-repeat-vip.svg'
export { ReactComponent as IconCloseVip } from './icon-close-vip.svg'
export { ReactComponent as IconBackVip } from './icon-back-vip.svg'
export { ReactComponent as IconCornerBottomLeft } from './icon-corner-bottom-left.svg'
export { ReactComponent as IconCornerBottomRight } from './icon-corner-bottom-right.svg'
export { ReactComponent as IconCornerTopLeft } from './icon-corner-top-left.svg'
export { ReactComponent as IconCornerTopRight } from './icon-corner-top-right.svg'
export { ReactComponent as IconDoubleVip } from './icon-double-vip.svg'
export { ReactComponent as IconMaximizeGridVip } from './icon-maximize-grid-vip.svg'
export { ReactComponent as IconSendVip } from './icon-send-vip.svg'
export { ReactComponent as IconMinimizeVip } from './icon-minimize-vip.svg'
export { ReactComponent as IconMaximizeVip } from './icon-maximize-vip.svg'
export { ReactComponent as IconUserVip } from './icon-user-vip.svg'
export { ReactComponent as IconVolumeMuteVip } from './icon-volume-mute-vip.svg'
export { ReactComponent as IconAutoPlayVip } from './icon-auto-play-vip.svg'
export { ReactComponent as IconChatCornerLeft } from './icon-chat-corner-left.svg'
export { ReactComponent as IconChatCornerRight } from './icon-chat-corner-right.svg'

export { ReactComponent as WinningNumber0Vip } from './winning-number-green-vip.svg'
export { ReactComponent as WinningNumber26Vip } from './winning-number-26-vip.svg'
export { ReactComponent as WinningNumber32Vip } from './winning-number-32-vip.svg'
export { ReactComponent as WinningNumberBlackVip } from './winning-number-black-vip.svg'
export { ReactComponent as WinningNumberRedVip } from './winning-number-red-vip.svg'

export { ReactComponent as IconChip1Vip } from './icon-chip-1-vip.svg'
export { ReactComponent as IconChip5Vip } from './icon-chip-5-vip.svg'
export { ReactComponent as IconChip10Vip } from './icon-chip-10-vip.svg'
export { ReactComponent as IconChip25Vip } from './icon-chip-25-vip.svg'
export { ReactComponent as IconChip100Vip } from './icon-chip-100-vip.svg'
export { ReactComponent as IconChip500Vip } from './icon-chip-500-vip.svg'
export { ReactComponent as IconChip50Vip } from './icon-chip-50-vip.svg'

export { ReactComponent as IconPupaVip } from './icon-pupa-vip.svg'
